name: fe_mobile_flutter
description: "Last term project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^1.4.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  pdf: ^3.11.0
  printing: ^5.13.3
  image_picker: ^1.1.2
  json_annotation: ^4.8.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/spaghetti.png
    - assets/burger.png
    - assets/pizza.png
    - assets/cheesy.jpg
    - assets/soup.jpg
    - assets/avata.png
    - assets/default.jpg
    - assets/chickenwings.png